server:
  port: 7890
spring:
  application:
    name: consumer_2
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.200.242:9092         #Kafka\u7684\u6D88\u606F\u4E2D\u95F4\u4EF6\u670D\u52A1\u5668
          zk-nodes: 192.168.200.242:2181        #Zookeeper\u7684\u8282\u70B9\uFF0C\u5982\u679C\u96C6\u7FA4\uFF0C\u540E\u9762\u52A0,\u53F7\u5206\u9694
          auto-create-topics: true
      bindings:
        input:    #input\u662F\u63A5\u6536\uFF0C\u8FD9\u91CC\u63A5\u6536\u6D88\u606F\u4E2D\u8F6C\u7C7B\u7684\u6D88\u606F
          destination: test
        myInput: #\u81EA\u5B9A\u4E49input
          destination: kafka-demo
          group: group  #\u5206\u7EC4\u7684\u7EC4\u540D
          consumer:     #\u5F00\u542F\u5206\u533A
            partitioned: true
        input_1: #\u81EA\u5B9A\u4E49input
          destination: kafka-demo1
          group: group1  #\u5206\u7EC4\u7684\u7EC4\u540D
          consumer:
            partitioned: true  #\u5F00\u542F\u5206\u533A
        input_2: #\u81EA\u5B9A\u4E49input
          destination: kafka-demo2
          group: group2 #\u5206\u7EC4\u7684\u7EC4\u540D
          consumer:
            partitioned: true  #\u5F00\u542F\u5206\u533A
        trans_input:
          destination: kafka-demo-trans
      #\u5206\u533A\u6570\u91CF
      instance-count: 2
      instance-index: 1
